# Generated by Django 3.1.4 on 2021-03-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210304_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
