# Generated by Django 3.1.4 on 2021-03-22 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20210316_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 22, 7, 9, 29, 152348, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
